### ISSUE TITLE
scatter bug: overcounting dots in a clique

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1023]
at [pnet plot](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22sampleScatter%22,%22name%22:%22Methylome%20TSNE%22,%22colorTW%22:{%22id%22:%22TSNE%20Category%22}}]}), hover over the orange ETMR tooltip shows something like `61 samples`
<img width="239" alt="image" src="https://github.com/stjude/proteinpaint/assets/1619109/87136855-2824-48db-9d27-881c0764c4fa">

but when u lasso the whole orange ETMR, there are n=28
<img width="148" alt="image" src="https://github.com/stjude/proteinpaint/assets/1619109/56e26660-fc88-45bb-9451-03c2232425fd">

**Comment by xzhou82** [comment]
false alarm not a bug! there are a bunch of Ref dots hidden underneath the selectable orange ones!

**Comment by xzhou82** [comment]
could clarify such case by showing a small text of `REF=40` at the tooltip heading

**Comment by airenzp** [comment]
Yes, I was about to let you know. Great

**Comment by xzhou82** [comment]
if it fools me it will fool others...

**Comment by xzhou82** [comment]
a better way to clarify is at the bottom of this lasso menu, display text `40 Ref samples are skipped`
