### ISSUE TITLE
Computation of hidden series significantly reduces performance of cuminc analysis

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#1037]
[Cardiomyopathy/hrtavg cuminc analysis](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22cuminc%22,%22settings%22:%7B%22cuminc%22:%7B%7D%7D,%22term%22:%7B%22id%22:%22Cardiomyopathy%22,%22q%22:%7B%7D%7D,%22term2%22:%7B%22id%22:%22hrtavg%22,%22q%22:%7B%22type%22:%22custom-bin%22,%22mode%22:%22discrete%22,%22lst%22:%5B%7B%22startunbounded%22:true,%22stop%22:200,%22stopinclusive%22:false,%22label%22:%22%3C200%22%7D,%7B%22start%22:200,%22startinclusive%22:true,%22stopunbounded%22:true,%22label%22:%22%E2%89%A5200%22%7D%5D%7D%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D) takes ~2sec

[Cardiomyopathy/chestrt cuminc analysis](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22cuminc%22,%22settings%22:%7B%22cuminc%22:%7B%7D%7D,%22term%22:%7B%22id%22:%22Cardiomyopathy%22,%22q%22:%7B%7D%7D,%22term2%22:%7B%22id%22:%22chestrt_yn%22,%22q%22:%7B%22type%22:%22custom-bin%22,%22mode%22:%22discrete%22,%22lst%22:%5B%7B%22startunbounded%22:true,%22stop%22:200,%22stopinclusive%22:false,%22label%22:%22%3C200%22%7D,%7B%22start%22:200,%22startinclusive%22:true,%22stopunbounded%22:true,%22label%22:%22%E2%89%A5200%22%7D%5D%7D%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D) takes ~8sec

The reason for the significant slowdown is that when one of the hidden series in the chest RT analysis (`exposed, dose unknown`) is analyzed, the analysis takes a long time to complete. See the following benchmarking results for each pairwise analysis:
```
"<200;≥200 0.0065 secs"
"<200;exposed, dose unknown 3.8478 secs"
"<200;unknown exposure 0.0048 secs"
"≥200;exposed, dose unknown 2.1418 secs"
"≥200;unknown exposure 0.0026 secs"
"exposed, dose unknown;unknown exposure 1.0938 secs"
```

It turns out that whenever the `exposed, dose unknown` series is analyzed, the analysis needs to undergo a permutation test (because of low sample size), which is the reason for the slowdown.

Therefore, it might be beneficial to only run the cuminc analysis for visible series. Changing a series from hidden to visible will lead to another server request, but this might be worth it considering that most of the time users will not need to unhide series that are hidden by default.

What are your thoughts @xzhou82 @siosonel ?

**Comment by siosonel** [comment]
@gavrielm We need to balance the performance gain of not doing unnecessary calculation, versus having to re-request data from the server when a series is hidden/made visible. 

It seems the issue is with low sample size, which may be also be the case for a visible series, not just those that are hidden by default. Is there an option to turn off pairwise comparison when at least one of the series has a low sample size, and in the UI we'll just note "analysis skipped for low sample series (N < 5)"? Maybe we can make that cutoff user-configurable, the user can accept the time-penalty if they want actual analysis results instead of the "skipped" message.

**Comment by gavrielm** [comment]
Ok that sounds good. The low sample size cutoff is currently controlled by this setting:
<img width="570" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/b2840402-fe6d-4b15-b9cd-15ebd9df1a18">

But this setting operates only on the client-side (i.e. the low sample sizes serieses will still undergo cuminc computation and then be hidden on the UI). I will change the setting to operate on the server-side to exclude low sample size serieses from the cuminc computation.
