### ISSUE TITLE
geneVariant barchart breaks

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1061]
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22term%22:{%22type%22:%22geneVariant%22,%22name%22:%22TP53%22}}}]}) looking into recent getData() changes

**Comment by xzhou82** [comment]
likely cause https://github.com/stjude/proteinpaint/commit/170b66aba69fcf00a8975af1d024833ba883bc6f

**Comment by siosonel** [comment]
the partjson template expects input `key1` to be an array, forcing geneVariant input data to have that shape fixes this issue
