### ISSUE TITLE
matrix defect: when filtering samples on a discrete numeric term, change the term to continuous breaks

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1088]
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22term%22:{%22name%22:%22TP53%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22name%22:%22BCOR%22,%22type%22:%22geneVariant%22}},{%22id%22:%22Gender%22},{%22id%22:%22Age%22},{%22id%22:%22TSNE%20Category%22}]}]}]}), Age term is discrete
first, hide a Age category, then change Age to continuous breaks 

TypeError: Cannot convert undefined or null to object
    at Function.values (<anonymous>)
    at Matrix.getLegendData (matrix.legend.js:97:33)
    at Matrix.getSerieses (matrix.serieses.js:123:25)

**Comment by siosonel** [comment]
Open session file to test: [issue.1088.txt](https://github.com/stjude/proteinpaint/files/13823012/issue.1088.txt)

**Comment by xzhou82** [comment]
yes it fixed the breakage. more issues remain:
1. Hide "<2" from age, turn age to continuous, Age row no longer shows in legend, making it a invisible filter
2. Hide "<2", edit age binning, breaks
