### ISSUE TITLE
remove the handling of groups from the geneset edit UI

### ISSUE THREAD

**Issue by siosonel** [stjude/proteinpaint#1146]
This will involve the partial reversion of recent changes to the geneset edit UI. Full reversion to a version before this week will require redoing tests and other improvements, which is not practical.

**Comment by xzhou82** [comment]
geneset edit ui can still handle groups. but groups should be optional

**Comment by siosonel** [comment]
closed by https://github.com/stjude/proteinpaint/pull/1154
