### ISSUE TITLE
minor bug with editing variable name on gene exp clustering

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#1195]
in GDC gliomas link, changed the variable name from 'Project Id' to 'Project' and submitted.
![image](https://github.com/stjude/proteinpaint/assets/77972514/e93f1573-1acc-46de-995e-d123168d7685)

Then edited groups to exclude some and dragged some to group 2. click submit
![image](https://github.com/stjude/proteinpaint/assets/77972514/109d2464-91bc-4c10-bc8f-1622b1b00a9d)

Variable name reverts to default
![image](https://github.com/stjude/proteinpaint/assets/77972514/b93efa6e-a795-4c36-8070-04a9b52dedc8)

**Comment by xzhou82** [comment]
thanks. can replicate with [pnet](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22term%22:{%22name%22:%22TP53%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22name%22:%22BCOR%22,%22type%22:%22geneVariant%22}},{%22id%22:%22Gender%22},{%22id%22:%22Age%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22TSNE%20Category%22}]}]}]})
