### ISSUE TITLE
To tackle the duplication of info table on GDC sunburst plot

### ISSUE THREAD

**Issue by akanksha-r** [stjude/proteinpaint#1308]
The table content displays on duplicate upon clicking the sunburst plot.
<img width="1648" alt="Screenshot 2024-02-08 at 5 07 21 PM" src="https://github.com/stjude/proteinpaint/assets/44287439/fe2d7825-862f-45fa-9177-6cf0449dd060">

**Comment by karishma-gangwani** [comment]
I guess now we can post images of GDC integrated pp tools here. except controlled data of course!

**Comment by xzhou82** [comment]
that's right. absolutely don't post controlled data
