### ISSUE TITLE
Odd violin shape for PRS term

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#1395]
Shape of [violin plot for PRS term](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22PGS000001_ceu_maf%22,%22q%22:{%22mode%22:%22continuous%22}}}],%22nav%22:{%22activeTab%22:1}}) appears very wide. Maybe because variability of data values is very low. Is this shape expected?

**Comment by xzhou82** [comment]
we're looking into it

**Comment by xzhou82** [comment]
caused by bandwidth with default value 5, which is way larger than the data range

**Comment by xzhou82** [comment]
https://github.com/stjude/proteinpaint/pull/1392
