### ISSUE TITLE
barchart overlay colors are incorrect

### ISSUE THREAD

**Issue by siosonel** [stjude/proteinpaint#1396]
[barchart-overlay-color.txt](https://github.com/stjude/proteinpaint/files/14454413/barchart-overlay-color.txt)

![Screenshot 2024-02-29 at 4 53 20 PM](https://github.com/stjude/proteinpaint/assets/411031/72a7cba1-ab65-4f0e-84e0-8e658058b7e0)

**Comment by xzhou82** [comment]
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22sex%22},%22term2%22:{%22id%22:%22diaggrp%22}}],%22nav%22:{%22activeTab%22:1}})
