### ISSUE TITLE
disco launched from matrix doesn't show mutation gene label

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1450]
[here](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22PNET%22,%22genome%22:%22hg19%22,%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22term%22:{%22name%22:%22TP53%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22name%22:%22BCOR%22,%22type%22:%22geneVariant%22}},{%22id%22:%22Gender%22},{%22id%22:%22Age%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22TSNE%20Category%22}]}]}]}), click on first sample/column > Disco, not showing gene label for mutations

direct disco from url can show those gene labels http://localhost:3000/?genome=hg19&dslabel=PNET&disco=1&sample=SJHGG030319_D1

please take a look if any issue with the way matrix calls disco

**Comment by aacic** [comment]
I've highlighted the sample displayed by  the url: http://localhost:3000/?genome=hg19&dslabel=PNET&disco=1&sample=SJHGG030319_D1

Clicking on the sample opens the same disco plot. 


<img width="1084" alt="Screenshot 2024-05-17 at 5 15 49 PM" src="https://github.com/stjude/proteinpaint/assets/32873451/240a8eb8-30ab-4c53-bf06-e2109343d21d">

Could you verify this @xzhou82 ?

**Comment by xzhou82** [comment]
yes it shows gene labels now
