### ISSUE TITLE
matrix: allow to add survival terms and show either exit status (0/1) or survival length (bar plot)

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1503]
not urgent but useful for neuroonc

**Comment by siosonel** [comment]
@xzhou82 idea: we can color code the barchart, like red for 1 and gray for 0/censored.

**Comment by xzhou82** [comment]
great point. may also change mode from bar (continuous time) to binary (not bar) of vital status of live/dead?
