### ISSUE TITLE
app card: new browser track card for BCF/VCF

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1508]
vcffile parameter is now replaced by `mds3bcffile` which accepts custom bcf file 

example of custom bcf without sample: http://localhost:3000/?genome=hg38&gene=kras&mds3bcffile=custom,hg38/clinvar.hg38.bcf.gz

example of custom bcf with sample: http://localhost:3000/?genome=hg38&gene=p53&mds3bcffile=custom,files/hg38/TermdbTest/TermdbTest.bcf.gz

**Comment by creilly8** [comment]
@xzhou82 Is there user documentation for this anywhere?
