### ISSUE TITLE
hiercluster: clicking on dict term row label breaks

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1520]
[test here](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:{%22header_mode%22:%22hidden%22},%22plots%22:[{%22chartType%22:%22hierCluster%22,%22genes%22:[{%22gene%22:%22DDX11L1%22},{%22gene%22:%22FAM138A%22},{%22gene%22:%22OR4F5%22},{%22gene%22:%22OR4F16%22},{%22gene%22:%22TP53%22},{%22gene%22:%22AKT1%22},{%22gene%22:%22KRAS%22},{%22gene%22:%22BCR%22},{%22gene%22:%22ITGAV%22},{%22gene%22:%22JAG1%22},{%22gene%22:%22JAG2%22},{%22gene%22:%22KCNJ8%22},{%22gene%22:%22LPL%22},{%22gene%22:%22LRPAP1%22},{%22gene%22:%22LUM%22},{%22gene%22:%22MSX1%22},{%22gene%22:%22NRP1%22},{%22gene%22:%22OLR1%22},{%22gene%22:%22PDGFA%22},{%22gene%22:%22PF4%22},{%22gene%22:%22PGLYRP1%22},{%22gene%22:%22POSTN%22},{%22gene%22:%22PRG2%22},{%22gene%22:%22PTK2%22},{%22gene%22:%22S100A4%22},{%22gene%22:%22SERPINA5%22},{%22gene%22:%22SLCO2A1%22},{%22gene%22:%22SPP1%22},{%22gene%22:%22STC1%22},{%22gene%22:%22THBD%22},{%22gene%22:%22TIMP1%22},{%22gene%22:%22TNFRSF21%22},{%22gene%22:%22VAV2%22},{%22gene%22:%22VCAN%22},{%22gene%22:%22VEGFA%22},{%22gene%22:%22VTN%22}],%22termgroups%22:[{%22name%22:%22Variables%22,%22lst%22:[{%22id%22:%22diaggrp%22}]}]}]})

err:

categorical.ts:120 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lst')
    at Object.postMain (categorical.ts:120:37)

this is urgent please fix it asap and we will release the fix to gdc. thanks

**Comment by congyu-lu** [comment]
> [test here](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:%7B%22header_mode%22:%22hidden%22%7D,%22plots%22:%5B%7B%22chartType%22:%22hierCluster%22,%22genes%22:%5B%7B%22gene%22:%22DDX11L1%22%7D,%7B%22gene%22:%22FAM138A%22%7D,%7B%22gene%22:%22OR4F5%22%7D,%7B%22gene%22:%22OR4F16%22%7D,%7B%22gene%22:%22TP53%22%7D,%7B%22gene%22:%22AKT1%22%7D,%7B%22gene%22:%22KRAS%22%7D,%7B%22gene%22:%22BCR%22%7D,%7B%22gene%22:%22ITGAV%22%7D,%7B%22gene%22:%22JAG1%22%7D,%7B%22gene%22:%22JAG2%22%7D,%7B%22gene%22:%22KCNJ8%22%7D,%7B%22gene%22:%22LPL%22%7D,%7B%22gene%22:%22LRPAP1%22%7D,%7B%22gene%22:%22LUM%22%7D,%7B%22gene%22:%22MSX1%22%7D,%7B%22gene%22:%22NRP1%22%7D,%7B%22gene%22:%22OLR1%22%7D,%7B%22gene%22:%22PDGFA%22%7D,%7B%22gene%22:%22PF4%22%7D,%7B%22gene%22:%22PGLYRP1%22%7D,%7B%22gene%22:%22POSTN%22%7D,%7B%22gene%22:%22PRG2%22%7D,%7B%22gene%22:%22PTK2%22%7D,%7B%22gene%22:%22S100A4%22%7D,%7B%22gene%22:%22SERPINA5%22%7D,%7B%22gene%22:%22SLCO2A1%22%7D,%7B%22gene%22:%22SPP1%22%7D,%7B%22gene%22:%22STC1%22%7D,%7B%22gene%22:%22THBD%22%7D,%7B%22gene%22:%22TIMP1%22%7D,%7B%22gene%22:%22TNFRSF21%22%7D,%7B%22gene%22:%22VAV2%22%7D,%7B%22gene%22:%22VCAN%22%7D,%7B%22gene%22:%22VEGFA%22%7D,%7B%22gene%22:%22VTN%22%7D%5D,%22termgroups%22:%5B%7B%22name%22:%22Variables%22,%22lst%22:%5B%7B%22id%22:%22diaggrp%22%7D%5D%7D%5D%7D%5D%7D)
> 
> err:
> 
> categorical.ts:120 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'lst') at Object.postMain (categorical.ts:120:37)
> 
> this is urgent please fix it asap and we will release the fix to gdc. thanks

Its caused by the unavailable genes in the link (termdbTest only has TP53, AKT1, KRAS, and BCR), removing other genes from the url then it will work: 
http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:%7B%22header_mode%22:%22hidden%22%7D,%22plots%22:%5B%7B%22chartType%22:%22hierCluster%22,%22genes%22:%5B%7B%22gene%22:%22TP53%22%7D,%7B%22gene%22:%22AKT1%22%7D,%7B%22gene%22:%22KRAS%22%7D,%7B%22gene%22:%22BCR%22%7D%5D,%22termgroups%22:%5B%7B%22name%22:%22Variables%22,%22lst%22:%5B%7B%22id%22:%22diaggrp%22%7D%5D%7D%5D%7D%5D%7D
