### ISSUE TITLE
error on info icon - SJLIFE

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#1555]
seeing this error when clicking info icon within data dictionary on ppr and local instance. 

![image](https://github.com/stjude/proteinpaint/assets/77972514/f9573ca8-9395-4551-8749-51fce5537a97)

**Comment by xzhou82** [comment]
this was caused by the adhoc publication term id getting out of sync. it's fixed in rebuild and now on surv2, please test https://viz.stjude.cloud/cancer-survivorship/visualization/st-jude-survivorship-portal~18

**Comment by gavrielm** [comment]
Works now. Thanks for the fix.
