### ISSUE TITLE
snplst/snplocus tabs show at filter ui

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1567]
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:{%22activeTab%22:3},%22termfilter%22:{%22filter%22:{%22type%22:%22tvslst%22,%22join%22:%22and%22,%22in%22:true,%22lst%22:[{%22type%22:%22tvs%22,%22tvs%22:{%22term%22:{%22id%22:%22diaggrp%22},%22values%22:[{%22key%22:%22Acute%20lymphoblastic%20leukemia%22}]}},{%22type%22:%22tvs%22,%22tvs%22:{%22term%22:{%22id%22:%22agedx%22},%22ranges%22:[{%22startunbounded%22:true,%22stop%22:10,%22stopinclusive%22:true}]}}]}}}). click AND, select option `+AND` and get below
it's on prod now. need to be suppressed
<img width="264" alt="image" src="https://github.com/stjude/proteinpaint/assets/1619109/f5fa752f-aba8-440b-a2f1-db96bb516977">

**Comment by gavrielm** [comment]
Also shows up after making custom variable in GROUPS tab:

<img width="422" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/d87456e1-b4f5-4756-bd62-341826fa5a76">
