### ISSUE TITLE
Incorrect minimum in descriptive statistics

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#1591]
Open this [barchart](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22doxorubicin_5%22}}],%22nav%22:{%22activeTab%22:1}}) and the minimum value shown in descriptive statistics is `-8888`. This is likely the value of an uncomputable value. Should only include computable values in descriptive statistics.

**Comment by xzhou82** [comment]
also [logistic outcome](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22logistic%22,%22outcome%22:{%22id%22:%22LV_Ejection_Fraction_3D%22}}]}) shows same issue, while linear outcome and violin is okay

**Comment by karishma-gangwani** [comment]
thanks for pointing out. I can try to look into it @gavrielm
