### ISSUE TITLE
hic bugs and issues

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1610]
Immediate issues/ in progress:
- [ ] allow to set width for chrpair and detailed views

Mid term issues: 

Long term issues:
- [ ] dom/colorScale.ts allow to change color stops

Completed:
- [x] Resolution header can show `5 Kb bp`. please fix
- [x] log(o/e) color bar wrong. show white at 0 value. display 0 value in ruler. add 1px spacing between ruler and color bar. use 3px as tick size
- [x] at hic app, on clicking button `Genome` should directly show cached view and do not re-request data, if the genome view is already cached
- [x] at detailed view edit menu, add radio button of "auto/fixed" for scale min/max - Group decided it was better to set a global max cutoff than adding this option. 
- [x] http://localhost:3000/example.hic.chr8.detail.html opens to super wide block, but plot looks correct (5Kb res and squares on the canvas). when checking same view from genome->chrpair, it shows inconsistency between stated bp resolution (5Kb) vs canvas showing rectangles from frag res
- [x] color scale tick label font size too small. increase
- [x] at chr pair view, X axis has bigger gap than Y from the canvas
- [x] for all views (whole-genome, chrpair, detailed) allow to define colorscale min/max in state. if provided, use; otherwise, calculate based on data and also save to state. allow to set range such as -2 to 6 - we decided against this and instead let the user define the max cutoff as a percentage. 
- [x] chrpair view won't show frag zoom, while single region tk can

**Comment by creilly8** [comment]
Addressed issues in PRs https://github.com/stjude/proteinpaint/pull/1628 and https://github.com/stjude/proteinpaint/pull/1645
