### ISSUE TITLE
Violin plot issues

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#163]
Can refer to this link: http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22cisplatin_5%22,%22q%22:{%22mode%22:%22continuous%22}},%22term2%22:{%22id%22:%22Hearing%20loss%22}}],%22nav%22:{%22activeTab%22:1}}

- Plots of CTCAE grades should be sorted in ascending order
- Uncomputable grades (e.g. “Not tested”) should be hidden from both the plot and the p-values table by default
- Should support divide by
- Creating a violin plot with term 1 and then overlaying term 2 does not show p-value table
- Should allow user to select colors (for term 1 and term 2)
- Setting symbol size=0 should make the symbols disappear (if user does not want any symbols)

Most of these features are already supported in the bar chart so you can refer to the bar chart code as a template.

**Comment by karishma-gangwani** [comment]
> Can refer to this link: [http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22cisplatin_5%22,%22q%22:{%22mode%22:%22continuous%22}},%22term2%22:{%22id%22:%22Hearing%20loss%22}}],%22nav%22:{%22activeTab%22:1}}](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22cisplatin_5%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%22term2%22:%7B%22id%22:%22Hearing%20loss%22%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D)
> 
> * Plots of CTCAE grades should be sorted in ascending order
> * Uncomputable grades (e.g. “Not tested”) should be hidden from both the plot and the p-values table by default
> * Should support divide by
> * Creating a violin plot with term 1 and then overlaying term 2 does not show p-value table
> * Should allow user to select colors (for term 1 and term 2)
> * Setting symbol size=0 should make the symbols disappear (if user does not want any symbols)
> 
> Most of these features are already supported in the bar chart so you can refer to the bar chart code as a template.

- [ label clicking and brushing for filtering and sample display are not supported for conditional term type. ]

**Comment by gavrielm** [comment]
Open [this link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22cisplatin_5%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D,%22term2%22:%7B%22id%22:%22Hearing%20loss%22%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D), switch to bar chart, switch back to violin plot and I get this error:

<img width="646" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/01495afc-6b80-4a4a-ab7b-00537ed34809">
