### ISSUE TITLE
density plot in numeric termsetting edit ui has clipped spread

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1665]
[test link](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22MB_meta_analysis%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22Confidence%20Score%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D%7D%5D%7D)
see clipped distribution towards max value of numeric scale
<img width="574" alt="image" src="https://github.com/stjude/proteinpaint/assets/1619109/ba6aecfa-dc58-4572-bd81-fe142c89703c">

**Comment by airenzp** [comment]
yes it is true. I will take a look.
