### ISSUE TITLE
app drawer: "Scatter Plot" card refactor

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1843]
create following examples.

example 1: "Tumor methylome tSNE", use the current PNET view in the app card

example 2: "Dictionary variables", use sjlife "Age (years) at SJLIFE baseline assessment" as X, "Left ventricular ejection fraction 3D" as Y, show the fitted curve

example 3: "Gene expression", i tried with [gdc data](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22GDC%22,%22genome%22:%22hg38%22,%22nav%22:{%22header_mode%22:%22hidden%22},%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22term%22:{%22type%22:%22geneExpression%22,%22gene%22:%22TP53%22,%22name%22:%22TP53%22},%22q%22:{%22mode%22:%22continuous%22}},%22term2%22:{%22term%22:{%22type%22:%22geneExpression%22,%22gene%22:%22AKT1%22,%22name%22:%22AKT1%22},%22q%22:{%22mode%22:%22continuous%22}}}]}) but doesn't work. will troubleshoot this first

**Comment by creilly8** [comment]
@xzhou82 The first two examples are ready in https://github.com/stjude/proteinpaint/tree/issue.1843. I might be able to figure out the third if I have more information.
