### ISSUE TITLE
categorical handler tries to modify a frozen object in gdc mds3 tk

### ISSUE THREAD

**Issue by creilly8** [stjude/proteinpaint#1877]
1. Use http://localhost:3000/?genome=hg38&gene=ENST00000407796&mds3=GDC
2. Click on the sample label -> click on Adenomas and Adenocarcinomas to create a subtrack
3. From the new Adenomas and Adenocarcinomas filter in the subtrack, click +AND. Click on any pill in the filter UI. The tip shows `« Back to variable selection`, with no ability to select filter criteria. 
<img width="690" alt="Screenshot 2024-07-18 at 10 13 06 AM" src="https://github.com/user-attachments/assets/1c9eaca7-92a9-41cd-ac82-fc7ea85d09f2">

Related to https://github.com/stjude/proteinpaint/issues/1571.

**Comment by xzhou82** [comment]
https://github.com/stjude/proteinpaint/pull/1882
