### ISSUE TITLE
flipping from violin to barchart does not set q.type for metabolite

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#1938]
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22redomics%22,%22genome%22:%22mm10%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22term%22:{%22type%22:%22metaboliteIntensity%22,%22name%22:%22PHOSPHORYLCHOLINE%22},%22q%22:{%22mode%22:%22continuous%22}}}]})

backend breaks because tw.q.type is not set. getData() tests if type=='regular-bin', and otherwise will look for custom bins which doesn't existfor the term 

strange that [gene exp](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22term%22:{%22type%22:%22geneExpression%22,%22gene%22:%22TP53%22,%22name%22:%22TP53%22},%22q%22:{%22mode%22:%22continuous%22}}}]}) works fine. on changing to barchart tab, the q.type is properly assigned

**Comment by xzhou82** [comment]
fyi @josephpowi you can watch it. wish you had caught it before

**Comment by josephpowi** [comment]
> fyi @josephpowi you can watch it. wish you had caught it before

I will look into it.

**Comment by josephpowi** [comment]
tw objects for gene expression and metaboliteIntensity are different. I think it will trigger the error from line 213 in server/src/termdb.matrix.js

{
  term: { gene: 'Mpl', type: 'geneExpression', name: 'Mpl' },
  q: {
    mode: 'continuous',
    descrStats: [
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object],
      [Object], [Object]
    ]
  },
  '$id': 'Oqkksw8MX4ubArKHCBWPWhGb3ds-'
}

{
  term: {
    name: 'PHOSPHORYLCHOLINE',
    type: 'metaboliteIntensity',
    __ancestors: [],
    __ancestorNames: [],
    bins: { default: [Object], min: 0.00000568, max: 3.69881 }
  },
  isAtomic: true,
  q: { mode: 'discrete', isAtomic: true },
  '$id': 'TI0cUKL8R+x/nchmO8KrHDdpKb4-'
}

**Comment by xzhou82** [comment]
please check my pr. it shows the actual cause
