### ISSUE TITLE
matrix survival row on hover should replace exit code with human readable names

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2014]
are the exit code hardcoded? does every survival term needs term.values{} to define the codes?

**Comment by congyu-lu** [comment]
> are the exit code hardcoded? does every survival term needs term.values{} to define the codes?

If the exit code has a label in the db (such as IHG, Mbmeta), we will use that label, otherwise its hardcoded "Exit code: ..."
![image](https://github.com/user-attachments/assets/a049e920-9e88-4bad-aa3c-0aaf0e15745a)
