### ISSUE TITLE
Stand alone image viewer

### ISSUE THREAD

**Issue by creilly8** [stjude/proteinpaint#2021]
Tasks:

- PR 1 (#2030):
   - [x] Create a stand alone wsimage viewer plot type accessible from `mass: state: {....`

- PR 2 (https://github.com/stjude/proteinpaint/pull/2034):
   - [x] Import new plot type in sampleView

- PR 3 (https://github.com/stjude/proteinpaint/pull/2034):
   - [x] Add new viewer to the app drawer
   - [x] Add example to url.html

**Comment by xzhou82** [comment]
it's best for sampleview to import this new viewer to reduce code dup

**Comment by creilly8** [comment]
> it's best for sampleview to import this new viewer to reduce code dup

Thanks. It's included in the plan above.
