### ISSUE TITLE
categorical tw handler code should allow term.values to be empty

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2066]
see line 63 of client/tw/CategoricalRouter.ts

**Comment by siosonel** [comment]
@xzhou82  is there a an example URL for testing? I'd like to figure whether the `term.values` can default to an empty object, or whether other code uses the logic `if (!term.values)` to do something, so in that case `term.values` must remain undefined.

**Comment by xzhou82** [comment]
please test with http://localhost:3000/?genome=hg38&gene=ENST00000407796&mds3=GDC
