### ISSUE TITLE
barchart: changing color for uncomputable category of numeric term breaks

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2073]
[test link](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22diaggrp%22},%22term2%22:{%22id%22:%22hrtavg%22}}],%22nav%22:{%22activeTab%22:1}})
at legend, click unknown exposure and change color, breaks

**Comment by siosonel** [comment]
@xzhou82 I'm closing this, I assume it was fixed by https://github.com/stjude/proteinpaint/pull/2072.

**Comment by xzhou82** [comment]
no it's still there
