### ISSUE TITLE
`getSupportedChartTypes()` should assess ds.cohort{addCharts{},hideCharts{}} and replace allowedChartTypes[]

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2229]
getSupportedChartTypes() does two things:
1. compute chart types that can work for a ds, based on term type and data type availability. e.g. if survival term is present, allow survival chart. this computing only generate common chart types.
2. return allowed chart types per subcohort. mass client will show chart buttons solely based on this
3. optionally, apply ds overrides from a new structure below. addCharts will add things, hideCharts will hide things. this is a better design than allowedChartTypes[] that does two things and lead to excessive config on datasets

```
cohort {
  addCharts: {
     bySubcohort: {
       <cohort1>: [ 'chartype1', ...]
     }
     list: [ 'chartype1', ...]
   }
   hideCharts: {
      // same structure as addCharts
   }
}
```
1. `bySubcohort{}` is chart type list per subcohort, this will be used for profile which has a subcohort-specific chart type we have to support
2. `list[]` is a flat list
3. both bySubcohort and list can be used at same time

**Comment by xzhou82** [comment]
may hold this off and coordinate with Airen's efforts

**Comment by siosonel** [comment]
why is `hideCharts` required? Would not listing a chart in `addCharts` be sufficient?

**Comment by xzhou82** [comment]
say if one ds wants to hide barchart, if we use just one structure, then
barchart has to be added to ALL other ds, this is too repetitive
compared to if using two structures for add/hide, only need a small change
to this ds
