### ISSUE TITLE
overlay barchart shows wrong data in log scale

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#2337]
[overlay barchart](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22diaggrp%22},%22term2%22:{%22id%22:%22racegrp%22}}],%22nav%22:{%22activeTab%22:1}}), change scale to log. looks wrong.
<img width="596" alt="image" src="https://github.com/user-attachments/assets/05f522d4-d80a-44bd-97f0-33ee88cfc15c">

**Comment by siosonel** [comment]
NOTE: It shouldn't be possible possible to have a scale for stacked bars (overlay term), the intermediate scales will be misleading. Technically each nested stacked bar segment scale should start from zero and have it's own scale (edited)

**Comment by xzhou82** [comment]
we will disable log scale?

**Comment by siosonel** [comment]
> we will disable log scale?

or do whichever is true below
- if the `log` radio option is clicked, do not show overlay option
- if there is an overlay, do not show `log` radio input
