### ISSUE TITLE
allow user to modify colors on the legend for matrix mclass 

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#2361]
currently, matrix legend for mutation classes does not allow changing color coding scheme. we can allow user to change the color to enhance the visualization of mutations, fusions, cnv etc.

**Comment by creilly8** [comment]
@karishma-gangwani, Do you have an example link?

**Comment by karishma-gangwani** [comment]
> @karishma-gangwani, Do you have an example link?

Hi @creilly8 try [this](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22TermdbTest%22,%22genome%22:%22hg38-test%22,%22nav%22:{%22header_mode%22:%22hidden%22},%22plots%22:[{%22chartType%22:%22matrix%22,%22termgroups%22:[{%22lst%22:[{%22term%22:{%22gene%22:%22TP53%22,%22type%22:%22geneVariant%22}},{%22term%22:{%22gene%22:%22AKT1%22,%22type%22:%22geneVariant%22}},{%22id%22:%22efs%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22agedx%22,%22q%22:{%22mode%22:%22continuous%22}},{%22id%22:%22diaggrp%22},{%22term%22:{%22gene%22:%22TP53%22,%22type%22:%22geneExpression%22}}]}],%22divideBy%22:{%22id%22:%22sex%22}}]})

similar to your implementation of changing color in mds3 tk legend the matrix can also allow the user to change colors for the different mutation classes from the rendered legend. currently, those colors are hardcoded. Let me know if you want to discuss more.

**Comment by siosonel** [comment]
@karishma-gangwani FYI of my conversation with @congyu-lu:

"In some ways, I'm hesitant to expose this feature by default for matrix plot. Or, we should ask GDC first whether their portal users should be able to change mclass colors. They had already requested custom high-contrast colors for their portal, not sure if they want users to override those. In other words, we should have a setting on whether this feature should be exposed or not."

**Comment by karishma-gangwani** [comment]
> @karishma-gangwani FYI of my conversation with @congyu-lu:
> 
> "In some ways, I'm hesitant to expose this feature by default for matrix plot. Or, we should ask GDC first whether their portal users should be able to change mclass colors. They had already requested custom high-contrast colors for their portal, not sure if they want users to override those. In other words, we should have a setting on whether this feature should be exposed or not."

That's understandable @siosonel but if I am selecting variables such as 'molecular subtypes' where there could be double digit groups then the colors get duplicated and for visualization purposes that doesn't look good. We can disable it for GDC if they don't think it's useful but this shouldn't be limited to GDC either way right? Can we keep it exposed by default for other datasets? I wouldn't want to show two different molecular subtypes in my visualization with the same colors. It looks very confusing and could be misleading. Does that make sense?

**Comment by siosonel** [comment]
@karishma-gangwani Ok, verified yesterday with Himanso and Sharon that this feature is okay to deploy to GDC portal. For the record, mostly I wanted to verify that it's okay for a user to be able to change mclass color in GDC portal, which Lou and JC had particular about. I don't have any concerns with a user being able to change colors for groupsettings, categorical, and other term.types.

**Comment by congyu-lu** [comment]
[like]  Lu, Congyu reacted to your message:
________________________________
