### ISSUE TITLE
Broken click event for hidden violin plots

### ISSUE THREAD

**Issue by creilly8** [stjude/proteinpaint#2367]
In [this example](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22hrtavg%22,%22q%22:{%22mode%22:%22continuous%22}}}],%22nav%22:{%22activeTab%22:1}}), hovering over the hidden categories indicates if the user clicks on the category label, the samples or separate plot will be added. Nothing happens on click.

**Comment by karishma-gangwani** [comment]
> In [this example](http://localhost:3000/?noheader=1&mass=%7B%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:%5B%7B%22chartType%22:%22summary%22,%22term%22:%7B%22id%22:%22hrtavg%22,%22q%22:%7B%22mode%22:%22continuous%22%7D%7D%7D%5D,%22nav%22:%7B%22activeTab%22:1%7D%7D), hovering over the hidden categories indicates if the user clicks on the category label, the samples or separate plot will be added. Nothing happens on click.

I added @airenzp to this if that's alright since she has been more in touch with the violin plot.

**Comment by xzhou82** [comment]
boxplot rendering of uncomputable category legend (whose tw.q.mode is continuous) is correct, and violin should do the same
