### ISSUE TITLE
Error: Clicking on parent term in SJLife 

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#2430]
In SJLife portal, within the data dictionary, search for 'liver disease'. This is a parent term and currently allows clicking, but an error message is thrown since no 'Type' is associated. Is it possible to enable loading the child term/tree when clicked on a non-dictionary type? 
![image](https://github.com/user-attachments/assets/9931d9c4-c09e-4521-8696-c65a81a0d6bc)

not sure who to assign.

**Comment by gavrielm** [comment]
Also issue with excluded parent terms being returned in search. For example, PRS parent terms are returned when searching for terms for cumulative incidence analysis, which should only return chronic health condition terms:

![image](https://github.com/user-attachments/assets/17a15d17-d724-464a-8385-3f850fd2c8ed)
