### ISSUE TITLE
Matrix - hover on samples

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#289]
![image](https://github.com/stjude/proteinpaint/assets/77972514/d3efe9f9-ef36-4630-9193-aeb71a9f5617)

In this view hovering over a sample for ATRX or TP53 mutation only does not show tooltip. 

dropdown - glioma
group cases by - primary diagnosis
sort by - IDH1
no. of cases - increase to 9000.

Hover also stops working after 2-3 disco plots are opened by clicking cell area.

**Comment by siosonel** [comment]
@karishma-gangwani I'm able to see the tooltip, except when hovering over the white background cells where there are no associated data.

![Screenshot 2023-07-07 at 9 49 19 AM](https://github.com/stjude/proteinpaint/assets/411031/c0f72765-5d2f-4b34-bf82-bf7a0fb9bc74)

**Comment by karishma-gangwani** [comment]
okay. let me try that again. Not sure why it doesn't show up for me sometimes.

**Comment by siosonel** [comment]
> okay. let me try that again. Not sure why it doesn't show up for me sometimes.

also, see if there are errors in the browser console

**Comment by siosonel** [comment]
@karishma-gangwani will close for now, unless more details or error log is provided to be able to replicate the issue

**Comment by karishma-gangwani** [comment]
okay. I don't see any errors on the console. If I encounter it again I will reach out @siosonel
