### ISSUE TITLE
Matrix - bugs

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#293]
![image](https://github.com/stjude/proteinpaint/assets/77972514/4c2feea6-a7c3-46f8-aea2-b60dae2cb335)

tried to create grouping - others (1), leukemias/lymphomas (2), cns related (3) and exclude 'not reported' clicked on apply and it added groups 1,2,3 in excluded and UI shows the excluded categories alongwith 'not reported'. is this by design or a bug?

**Comment by xzhou82** [comment]
it's a known issue

**Comment by karishma-gangwani** [comment]
okay. I did not see it on the Word doc.

**Comment by karishma-gangwani** [comment]
![image](https://github.com/stjude/proteinpaint/assets/77972514/e24dc06b-f7b7-4f37-a502-0493c10721a8)

increase case size to 10k,  sort cases by input data order and sort by the first gene - breaks and throws error in console.

**Comment by karishma-gangwani** [comment]
not a bug - some variables show a lot of white space between controls and matrix. 

![image](https://github.com/stjude/proteinpaint/assets/77972514/ef488b36-72d4-4ff9-aa6f-3e9f116a7254)

**Comment by karishma-gangwani** [comment]
![image](https://github.com/stjude/proteinpaint/assets/77972514/015f955f-b10c-46f5-8940-2f6518327fbf)

not a bug - should the label 'Sample' be replaced by Case? since case is being used everywhere for GDC

**Comment by karishma-gangwani** [comment]
![image](https://github.com/stjude/proteinpaint/assets/77972514/0f05d121-fa19-4b7f-8038-814c8d899fd7)

click on gene label and replace by 'Disease type' shows this message

**Comment by karishma-gangwani** [comment]
replace gene term (TP53) with age at diagnosis shows this humongous legend.

![image](https://github.com/stjude/proteinpaint/assets/77972514/806d0d7e-222c-4d21-af13-727f44d88192)

**Comment by karishma-gangwani** [comment]
Deselect cgc genes and click submit, open gene set edit ui still shows blue checkmark. 

![image](https://github.com/stjude/proteinpaint/assets/77972514/6d452041-e046-4810-8910-859bf1d6ea10)

**Comment by karishma-gangwani** [comment]
error with msigdb gene set

![image](https://github.com/stjude/proteinpaint/assets/77972514/2eb27213-598c-476a-b819-a7ff7c446cfa)

dropdown glioma - load msigdb genes for CP canonical - KEGG_APOPTOSIS or any other - logs an error to the console
