### ISSUE TITLE
improve fusion representation in matrix

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#374]
now the sv/fusion events passed to matrix will contain new attribute `pairlst[]`, this allows to generate the correct fusion event label, as `(pairlst[0].a.name || pairlst[0].a.chr) + '::'+(pairlst[0].b.name||pairlst[0].b.chr)`
thus, hover over a matrix cell with svfusion events should display this label in toolti

next, clicking on such a cell should show an option to launch svgraph, besides Disco etc. we can look into the coding

**Comment by siosonel** [comment]
Partially addressed by https://github.com/stjude/proteinpaint/pull/387.
