### ISSUE TITLE
egfr T790M could be germline

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#464]
![image](https://github.com/stjude/proteinpaint/assets/77972514/8ab7b76e-7641-44e5-9b80-c884e18a65ea)

EGFR T790M could be germline variants.

**Comment by xzhou82** [comment]
why?

**Comment by karishma-gangwani** [comment]
I saw some papers where it's been misclassified as a somatic variant. But this variant can be acquired or inherited.

**Comment by xzhou82** [comment]
shouldn't be. both cases have `Normal depth` so they are from tumor-germline paired call and will rule out germline mutation
<img width="221" alt="image" src="https://github.com/stjude/proteinpaint/assets/1619109/187b0908-be60-4a4e-90e6-df748a5418c2">
