### ISSUE TITLE
Bins out of order in violin plot when boundary inclusion set to "start < x <= end"

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#488]
When making violin plot with overlay: http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22plots%22:[{%22chartType%22:%22summary%22,%22term%22:{%22id%22:%22agedx%22,%22q%22:{%22mode%22:%22continuous%22}},%22term2%22:{%22id%22:%22doxorubicin_5%22}}],%22nav%22:{%22activeTab%22:1}}

Editing bins of overlay term to `0, 100, 300` and setting boundary inclusion to `start < x <= end` will cause the `<=0` bin to show up at the bottom of plot:
<img width="729" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/00eaa712-03a3-4f56-832a-a0fefb1ffab2">

Need to fix the sorting code so that the `<=0` bin will show up at top of plot.

**Comment by karishma-gangwani** [comment]
Is this issue supposed to be in sjpp?

**Comment by gavrielm** [comment]
I don't think so. It's a pp repo issue.
