### ISSUE TITLE
disco - female circos should not be displaying 'Y' chr

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#601]
Y chr band for female cases looks misleading. I think we should leave that empty (no label) for now or completely remove it. 
![image](https://github.com/stjude/proteinpaint/assets/77972514/faf388e2-cb11-4f0e-a6b0-ee56a1dbf3af)

**Comment by xzhou82** [comment]
thanks for the idea it makes perfect sense. i can already imagine how to implement it. it will all be cross-checking of genome/ds config and sample data, at the end pp code will decide if to include Y or not as a way to customize chr list. no change from disco code needed

**Comment by karishma-gangwani** [comment]
ok pls include me in. I can work on it.

**Comment by xzhou82** [comment]
should keep it for ...

**Comment by xzhou82** [comment]
post discussion with both GDC and Giles. will keep it unchanged for now
