### ISSUE TITLE
Cannot search by rsID in genome browser

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#603]
Open http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22} -> Click on genome browser -> enter rsID that is known to be in database (e.g., `rs6689879`) -> cannot find rsID

**Comment by xzhou82** [comment]
you can search it on prp1. our local slice of dbsnp bb file has only tp53

**Comment by gavrielm** [comment]
Sorry about that. But I did get this error on prp1: Click on genome browser -> enter rsID `rs6537790` (which is in our db) -> error is thrown.

I think this is because this variant doesn't pass our variant filters (it is in polymer region), so no data is passed to the browser?

**Comment by xzhou82** [comment]
thanks i can replicate this issue locally with rs1642785 at [tp53](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22genomeBrowser%22,%22geneSearchResult%22:{%22chr%22:%22chr17%22,%22start%22:7666657,%22stop%22:7688274}}]}) looking into it now

**Comment by xzhou82** [comment]
https://github.com/stjude/proteinpaint/pull/607
