### ISSUE TITLE
Undefined categories in groups for logistic outcome

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#663]
sjlife portal (http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22}) -> regression analysis -> logistic -> categorical outcome variable (e.g., `Genetically defined race`) -> Edit -> undefined group categories.

Not sure if this has been a long term issue or if it is related to the groupsetting refactoring.

**Comment by xzhou82** [comment]
thanks for spotting it
@creilly8
