### ISSUE TITLE
Unclear binary grouping for "health status rating"

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#690]
[Load health status rating as logistic outcome](http://localhost:3000/?noheader=1&mass={%22genome%22:%22hg38%22,%22dslabel%22:%22SJLife%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22regression%22,%22regressionType%22:%22logistic%22,%22outcome%22:{%22id%22:%22health%22}}]}) -> Edit -> Default groupings are not correct

<img width="409" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/7cf4d92d-d9ff-4a06-b7a0-2c3dbbfbd7fa">

Groupings should show same category names that are displayed in bar chart:

<img width="721" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/e585a7a7-1a7b-4dc8-a3b6-326bbdf7a141">

**Comment by xzhou82** [comment]
thanks for spotting! noticed something else will create new issue on it
