### ISSUE TITLE
text rendering in canvas is off vertically, on prp3

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#708]
https://proteinpaint.stjude.org/?genome=hg38&block=1&position=chr8:127738453-127739192
right now this:
<img width="53" alt="image" src="https://github.com/stjude/proteinpaint/assets/1619109/e9685662-f2c8-4840-aa7f-3aefae293071">

should be this:
<img width="49" alt="image" src="https://github.com/stjude/proteinpaint/assets/1619109/08f162f4-115f-4cd4-8dda-224e1645ac06">

**Comment by xzhou82** [comment]
inspecting prp3 code found it's using up to date canvas (it's not using podman yet)

> [genomeuser@splpdmzpp01 ~]$ more /opt/app/pp/active/node_modules/canvas/package.json 
> {
>   "name": "canvas",
>   "description": "Canvas graphics API backed by Cairo",
>   "version": "2.9.3",

**Comment by xzhou82** [comment]
cairo is installed, at version 1.15.12

> [genomeuser@splpdmzpp01 ~]$ rpm -q cairo-devel
> cairo-devel-1.15.12-6.el8.x86_64

according to https://www.cairographics.org/releases/, 1.15.12 is from 2018!

local mac installed 1.16

> brew info cairo
> ==> cairo: stable 1.16.0 (bottled), HEAD

**Comment by xzhou82** [comment]
alex tried

sudo dnf update 

> cairo-devel

But it says:

> Updating Subscription Management repositories.
> Last metadata expiration check: 1:20:04 ago on Fri 06 Oct 2023 02:18:21 PM CDT.
> Dependencies resolved.
> Nothing to do.
> Complete!

**Comment by siosonel** [comment]
this is being done in `container/deps/Dockerfile`, line 60: `sed -i '/<blank>/,/<\/blank>/d' /etc/fonts/fonts.conf`, may need to do something similar for native RHEL

**Comment by xzhou82** [comment]
now renders correctly on prp2 podman. will be fixed when podman is deployed on prp1

**Comment by xzhou82** [comment]
fixed with podman
