### ISSUE TITLE
matrix - after adding filter and closing a chart

### ISSUE THREAD

**Issue by karishma-gangwani** [stjude/proteinpaint#711]
I am seeing this error after I add a filter and close a chart from a previously loaded 'group' from the groups tab.
![image](https://github.com/stjude/sjpp/assets/77972514/2c798840-131c-4a2d-8ebd-6bde371a9dad)

![image](https://github.com/stjude/proteinpaint/assets/77972514/c19ea8fa-7cdf-4040-84a6-bf30975ae2ac)

**Comment by xzhou82** [comment]
does it still happen in incognito? [see this per Edgar](https://stackoverflow.com/questions/72494154/a-listener-indicated-an-asynchronous-response-by-returning-true-but-the-messag)
if this is the reason,  then which chrome extension do you have?

**Comment by karishma-gangwani** [comment]
I haven't seen it again. Can close this for now.
