### ISSUE TITLE
No adjustment for ancestry in TOPMed cohort

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#718]
Open [sjlife genome browser](http://localhost:3000/?noheader=1&mass={%22dslabel%22:%22SJLife%22,%22genome%22:%22hg38%22,%22nav%22:{%22activeTab%22:1},%22plots%22:[{%22chartType%22:%22genomeBrowser%22,%22geneSearchResult%22:{%22chr%22:%22chr17%22,%22start%22:7666657,%22stop%22:7688274}}]}). Here are association results for gnomAD:

<img width="1391" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/c1e6ea54-c8ee-4574-9903-373697206444">

Here are association results for TOPMed:

<img width="1391" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/62f42844-fc5f-4ec7-a827-d26ce6a60675">

The large difference in results is due to not adjusting the ancestry background in TOPMed. For example, here are results when we compare different ancestries:

<img width="1396" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/47e7c0b4-592f-4a83-843a-f31d6d6e60a2">

**Comment by xzhou82** [comment]
TOPmed does not come with ancestry specific AF, thus cannot adjust with the
gnomAD method

**Comment by gavrielm** [comment]
Ok. I will close issue then.
