### ISSUE TITLE
Data download issues

### ISSUE THREAD

**Issue by gavrielm** [stjude/proteinpaint#741]
Data download issues:

- Default `q.mode` for continuous variable should be `continuous`, not `discrete`

- Do not need this display when downloading list of variants:
<img width="1051" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/4e183d42-27e1-4812-ab3c-a684429915ed">

- Do not need settings related to effect allele frequency when downloading locus of variants:
<img width="1993" alt="image" src="https://github.com/stjude/proteinpaint/assets/8413053/f209b281-3255-4000-9a22-204cbb987e10">

**Comment by xzhou82** [comment]
agreed
