### ISSUE TITLE
Broken links in install.pp.js

### ISSUE THREAD

**Issue by wsp00nr** [stjude/proteinpaint#756]
Links in utils/install.pp.js to https://pecan.stjude.cloud are broken. E.g. 

```
% node utils/install.pp.js -c install.conf
Directory exists: /home/containers/proteinpaint/tp
Directory exists: /homel/containers/proteinpaint/cache
Directory exists: /home/containers/proteinpaint/cache/ssid
Directory exists: /home/containers/proteinpaint/tp/anno/
Directory exists: /home/containers/proteinpaint/tp/anno/db/
Directory exists: /home/containers/proteinpaint/tp/genomes/
Downloading file for /home/containers/proteinpaint/tp/genomes/hg19.gz from https://pecan.stjude.cloud/static/hg19/hg19.gz
wget: unable to resolve host address ‘pecan-legacy.stjude.cloud’
node:child_process:960
    throw err;
    ^
```

**Comment by xzhou82** [comment]
Hi Will, do you use our docker image? If so you can try
"utils/public-support-files-download.sh" instead. We may deprecate the
install.pp.js script. The shell script only has data for hg19 and hg38. If
you need a different genome, let me know.

**Comment by wsp00nr** [comment]
I use the container and eventually found
utils/public-support-files-download.sh which allowed me to deploy.
Suggestion: update container/README.md (and the wiki pages) to indicate
that utils/public-support-files-download.sh should be used.

Thanks :)  Will

**Comment by siosonel** [comment]
@wsp00nr Where did you see the instructions to use `node utils/install.pp.js -c install.conf`? We'd like to review that document, I'm not able to find that instruction text in our repo. Maybe it's in a Google Doc or a particular wiki?

**Comment by xzhou82** [comment]
Please see if this fix is okay https://github.com/stjude/proteinpaint/pull/878
