### ISSUE TITLE
aachange is not based on canonical isoform in disco

### ISSUE THREAD

**Issue by xzhou82** [stjude/proteinpaint#813]
test with mbmeta link in url.html
if related to https://github.com/stjude/proteinpaint/issues/792

**Comment by xzhou82** [comment]
single sample data are written in individual json files
@josephpowi what's the script to make the file? when parsing mutations from bcf it should use aachange of canonical isoform

**Comment by xzhou82** [comment]
we should fix the script and rerun the data output. while doing this also change to using string sample name as file names, no longer use integer names @congyu-lu

**Comment by josephpowi** [comment]
the isoform is selected based on the consequence level. The one with highest level was selected.

**Comment by xzhou82** [comment]
no need to make change to json file name (integer to string names). we will do integer-string change to bcf first

**Comment by xzhou82** [comment]
i just verified that this is fixed now after pulling updated mutationpersample json files. thanks

**Comment by josephpowi** [comment]
> i just verified that this is fixed now after pulling updated mutationpersample json files. thanks

Yes. It is fixed in Nov I guess
