### ISSUE TITLE
Inform the user of the caching status of GDC sample IDs

### ISSUE THREAD

**Issue by siosonel** [stjude/proteinpaint#840]
When the PP server restarts within the GDC backend, the caching of sample IDs can take >2 minutes. If a user opens a gene expression plot while the caching is not done, they could see an incomplete gene expression plot with only a few columns. 

Maybe the `/genomes` or `/topVariablyExpressedGenes` response could include information on how many samples have been cached at the time of the request and whether it's done caching, so we can inform the user with a message in the sandbox of the gene expression plot

**Comment by xzhou82** [comment]
https://github.com/stjude/proteinpaint/pull/841
